image: debian:latest

before_script:
    - apt-get update -q
    - apt-get install -qy gcc clang make gperf ragel valgrind

check:
    script:
        # TODO: remove LENGTH_TYPE override when Debian updates to gperf >= 3.1
        - make CPPFLAGS=-DLENGTH_TYPE=unsigned
        - make check
