test:debian:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian
    script: &SCRIPT
        - export MAKEFLAGS="-j$(mk/nproc.sh)" WERROR=1
        - make check CC=gcc
        - make clean
        - make check CC=clang
