test:debian:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian-12
    script:
        - export MAKEFLAGS="-j$(mk/nproc.sh)" WERROR=1 V=1
        - make check CC='ccache ${CC:-gcc}'
        - make install
        - tally

        - make CC='ccache gcc'
        - make CC='ccache clang'
        - make CC='ccache arm-linux-gnueabihf-gcc'
        - make CC='ccache aarch64-linux-gnu-gcc'

        - export LDFLAGS=-static
        - make CC='ccache gcc'
        - make CC='ccache clang'
        - make CC='ccache arm-linux-gnueabihf-gcc'
        - make CC='ccache aarch64-linux-gnu-gcc'
