#include "parse.h"
#include "languages.h"

static const ParserFunc parsers[NUM_LANGUAGES] = {
    [ADA] = NULL,
    [APPLESCRIPT] = NULL,
    [ASSEMBLY] = NULL,
    [AWK] = NULL,
    [BATCHFILE] = NULL,
    [C] = parse_c,
    [CHEADER] = parse_c,
    [COFFEESCRIPT] = NULL,
    [COMMONLISP] = NULL,
    [CPLUSPLUS] = parse_c,
    [CPLUSPLUSHEADER] = parse_c,
    [CSHARP] = parse_c,
    [CSS] = NULL,
    [D] = parse_c,
    [DART] = parse_c,
    [EMACSLISP] = NULL,
    [GO] = parse_c,
    [GPERF] = NULL,
    [GROOVY] = parse_c,
    [HASKELL] = NULL,
    [HTML] = NULL,
    [INI] = NULL,
    [JAVA] = parse_c,
    [JAVASCRIPT] = parse_c,
    [JSON] = NULL,
    [LEX] = NULL,
    [LUA] = NULL,
    [MAKE] = NULL,
    [MALLARD] = NULL,
    [MARKDOWN] = NULL,
    [MOONSCRIPT] = NULL,
    [OBJECTIVEC] = parse_c,
    [PERL] = NULL,
    [PHP] = parse_c,
    [PKGCONFIG] = NULL,
    [PROTOBUF] = NULL,
    [PYTHON] = NULL,
    [RUBY] = NULL,
    [RUST] = parse_c,
    [SCHEME] = NULL,
    [SCSS] = NULL,
    [SED] = NULL,
    [SHELL] = NULL,
    [SQL] = NULL,
    [TCL] = NULL,
    [TEX] = NULL,
    [VALA] = parse_c,
    [VIML] = NULL,
    [XML] = NULL,
    [YACC] = NULL,
    [YAML] = NULL,
};

ParserFunc lookup_parser(Language language) {
    return parsers[language];
}
