.TH TALLY 1 "June 2017"
.SH NAME
tally \- count lines of source code
.SH SYNOPSIS
.B tally
.RB [ \-sidh ]
.RI [ PATH ]...
.SH OPTIONS
.TP
.B \-s
Show line counts per language (default)
.TP
.B \-i
Show line counts per file
.TP
.B \-d
Show detected file types
.TP
.B \-h
Show usage information
.SH COPYRIGHT
Copyright \(co 2014-2017 Craig Barnes.
.SH LICENSE
GNU GPL version 2 or later <https://gnu.org/licenses/gpl.html>.
.br
There is NO WARRANTY, to the extent permitted by law.
