.TH TALLY 1 "July 2025"
.SH NAME
tally \- count lines of source code
.SH SYNOPSIS
.B tally
.RB [ \-sidah ]
.RI [ PATH ]...
.SH OPTIONS
.TP
.B \-s
Show line counts per language (default)
.TP
.B \-i
Show line counts per file
.TP
.B \-d
Like \fB\-i\fR, but also showing unknown/ignored files
.TP
.B \-a
All of the above (equivalent to \fB\-sid\fR)
.TP
.B \-h
Show usage information
.SH COPYRIGHT
Copyright \(co 2014-2025 Craig Barnes.
.SH LICENSE
GNU GPL version 2
<https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
.br
There is NO WARRANTY, to the extent permitted by law.
