.TH TALLY 1 "January 2024"
.SH NAME
tally \- count lines of source code
.SH SYNOPSIS
.B tally
.RB [ \-sidh ]
.RI [ PATH ]...
.SH OPTIONS
.TP
.B \-s
Show line counts per language (default)
.TP
.B \-i
Show line counts per file
.TP
.B \-d
Show detected file types
.TP
.B \-h
Show usage information
.SH COPYRIGHT
Copyright \(co 2014-2024 Craig Barnes.
.SH LICENSE
GNU GPL version 2
<https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
.br
There is NO WARRANTY, to the extent permitted by law.
